name: ðŸ”’ Identify and close stale issues and PRs

on:
  schedule:
    - cron: '15 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”’ Close stale issues and PRs
        uses: actions/stale@v9
        with:
          stale-issue-message:
            This issue has been identified as stale because it
            has gone 14 days with no activity.

            The issue will be closed in 5 days. If this is incorrect,
            simply comment on the issue, or remove the stale label.
          stale-pr-message:
            This pull request has been identified as stale because
            it has gone 14 days with no activity.

            The pull request will be closed in 5 days. If this is incorrect,
            simply comment on the PR, remove the label, or merge the PR.

            Reminder, once a PR is approved, and checks have passed,
            you **can merge it yourself.**
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 14
          days-before-close: 5
          exempt-issue-labels: "work-in-progress"
          exempt-pr-labels: "work-in-progress"
